[package]
name = "piEstim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
indicatif = "0.16.2"
num-bigint = "0.4.3"
num-rational = "0.4.0"
